### ISSUE TITLE
Problems with imports

### ISSUE THREAD

**Issue by andrei-polukhin** [michaelhelmick/linkedin#15]
During importing the `LinkedinAPI` class from your package, it throws an error
```
from urlparse import parse_qsl
ModuleNotFoundError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/.local/lib/python3.8/site-packages/linkedin.py", line 13, in <module>
    from cgi import parse_qsl
ImportError: cannot import name 'parse_qsl' from 'cgi' (/usr/lib/python3.8/cgi.py)
```
I was wondering if you could resolve these problems with your imports.

**Comment by andrei-polukhin** [comment]
No activity, so I'll close the issue.
